name: Deploy to Firebase (Test & Production)

on:
  push:
    branches:
      - test
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Configure GCP Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_RUTA: "${{ runner.temp }}/gcp-key.json"
        run: |
          # Escapar las comillas dobles dentro del JSON del secreto GCP
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | sed 's/"/\\"/g' > $GOOGLE_APPLICATION_CREDENTIALS_RUTA
          export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS_RUTA
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS_RUTA

      - name: Debug GCP Credentials
        run: cat $GOOGLE_APPLICATION_CREDENTIALS

      - name: Save GCP Credentials for Debugging
        uses: actions/upload-artifact@v4
        with:
          name: gcp-key
          path: ${{ runner.temp }}/gcp-key.json

      - name: Build Project
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-key.json"
        run: npm run build

      - name: Select Firebase Project and Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            firebase use prod
          else
            firebase use test
          fi
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
