name: Deploy to Firebase (Test & Production)

on:
  push:
    branches:
      - test
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Configure GCP Credentials for GitHub Actions
        env:
          GOOGLE_APPLICATION_CREDENTIALS_GITHUB: "${{ runner.temp }}/gcp-actions-key.json"
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "${{ secrets.GCP_ACTIONS_SERVICE_ACCOUNT_KEY_PRD }}" > $GOOGLE_APPLICATION_CREDENTIALS_GITHUB
          else
            echo "${{ secrets.GCP_ACTIONS_SERVICE_ACCOUNT_KEY_DEV }}" > $GOOGLE_APPLICATION_CREDENTIALS_GITHUB
          fi
          export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS_GITHUB

      - name: Configure GCP Credentials for Secret Manager
        env:
          GOOGLE_APPLICATION_CREDENTIALS_SECRET_MANAGER: "${{ runner.temp }}/gcp-secret-manager-key.json"
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "${{ secrets.GCP_SECRET_MANAGER_SERVICE_ACCOUNT_KEY_PRD }}" > $GOOGLE_APPLICATION_CREDENTIALS_SECRET_MANAGER
          else
            echo "${{ secrets.GCP_SECRET_MANAGER_SERVICE_ACCOUNT_KEY_DEV }}" > $GOOGLE_APPLICATION_CREDENTIALS_SECRET_MANAGER
          fi
          export GOOGLE_APPLICATION_CREDENTIALS_SECRET_MANAGER=$GOOGLE_APPLICATION_CREDENTIALS_SECRET_MANAGER

      - name: Build Project
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-actions-key.json"
        run: npm run build

      - name: Select Firebase Project and Deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-actions-key.json"
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            firebase deploy --only hosting --project sozu-admin
          else
            firebase deploy --only hosting --project sozu-admin-dev
          fi
